version: "turku-1.1"

services:
    db:
        container_name: linkedevents-db
        build: ./docker/postgres/
        restart: always
        environment:
            POSTGRES_USER: linkedevents
            POSTGRES_PASSWORD: linkedevents
            POSTGRES_DB: linkedevents
        volumes:
            - db_data:/var/lib/postgresql
    api:
        container_name: linkedevents-api
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash -c 'tail -f /dev/null'
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DATABASE_URL=postgis://linkedevents:linkedevents@db/linkedevents
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    db_data:
