services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db_linked_data:/var/lib/postgresql/data
      - linked_media:/var/www/media
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  db_linked_data:
  linked_media:
