services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: postgis://linkedevents:linkedevents@db:5432/linkedevents
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=linkedevents
      - POSTGRES_PASSWORD=linkedevents
      - POSTGRES_DB=linkedevents
    volumes:
      - db_linked_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db_linked_data:
