services:
  api:
    build:
      context: .
      target: development
    command: start_linked_dev_server
    volumes:
      - .:/srv/app
      - ./static:/var/www/static/

volumes:
  static-files:
