name: Linked Events CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: linkedevents
          POSTGRES_PASSWORD: linkedevents
          POSTGRES_DB: linkedevents
          DEBUG: true
          SECRET_KEY: le_secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext python-dev libpq-dev gdal-bin -y
          psql -h localhost -U linkedevents -d linkedevents -c "create extension hstore;"
        env:
          PGPASSWORD: linkedevents
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Apply migrations
        env:
          DATABASE_URL: postgis://linkedevents:linkedevents@localhost/linkedevents
          DEBUG: true
          SECRET_KEY: le_secret
        run: |
          python3 manage.py migrate
      - name: Compile translations
        run: |
          python3 manage.py compilemessages --locale en --locale fi --locale sv
      - name: Run tests
        env:
          DATABASE_URL: postgis://linkedevents:linkedevents@localhost/linkedevents
          DEBUG: true
          SECRET_KEY: le_secret
        run: |
          pytest --cov . --doctest-modules
